[version]
current = "0.4.0"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
'''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "Cargo.toml"
search = 'version = "{current_version}"'

[[file]]
src = "flake.nix"
search = 'version = "{current_version}";'

[[before_commit]]
name = "Check formatting"
cmd = "cargo fmt -- --check"

[[before_commit]]
name = "Build"
cmd = "cargo build"

[[before_commit]]
name = "Run tests"
cmd = "cargo test"

[[before_commit]]
name = "Run clippy"
cmd = "cargo clippy"

[[before_commit]]
name = "Nix build"
cmd = "nix build"
